### ISSUE TITLE
Screenshots

### ISSUE THREAD

**Issue by JuliaWolska** [leiradel/RASuite#10]
The best would be to preset it to make unfiltered images in the resolution native for used platform (to use them for making accurate and crisp achievement icons). Hotkey for screenshots: PrtSc or F12

**Comment by leiradel** [comment]
Implemented in https://github.com/leiradel/RASuite/commit/d9e26c630b261cd24e696f85b6cfbce84e260def

**Comment by meleu** [comment]
@leiradel is it possible to save the image files on the same directory as RALibretro.exe instead of Desktop?
