### ISSUE TITLE
Alternative save state hotkeys (similiar to RANes and RASnes)

### ISSUE THREAD

**Issue by JuliaWolska** [leiradel/RASuite#11]
Load state: F10, F1, F2...F9
Load current slot: F11
Save current slot: Backspace
Save state: shift+F10, shift+F1, shift+F2...shift+F9
Switch slot: 0, 1, 2...9
Previous slot: shift+-
Next slot: shift++

**Comment by leiradel** [comment]
@meleu can you talk to @JuliaWolska and agree in the key bindings that we'll have in RALibretro?

**Comment by meleu** [comment]
@JuliaWolska I've put here the current default shortcuts: https://github.com/RetroAchievements/docs/wiki/RALibretro

@leiradel maybe we could convert her request here to "please, provide a way to customize shortcuts". :wink:

**Comment by JuliaWolska** [comment]
I'm used to those hotkeys because they are utilized among 3 emulators (RAFCEUx, RASnes9x and RAVBA - 5 systems), and allow quick and precise switching between different postions in game, which is often useful in searching for solid address.

**Comment by meleu** [comment]
@leiradel I agree with Salsa. Her suggestions "allow quick and precise switching between different postions in game, which is often useful in searching for solid address".

Trying to explain her suggestions more clearly:

function | current shortcut | suggestion
:--------:|:--------------------:|:-------------:
Load state from slot 1, 2, .., 9, 0 | **N.A.** | F1, F2, ..., F9, F10
Load current slot | F8 | F11
Save current slot | F5 | Backspace
Save state to slot  1, 2, .., 9, 0 | **N.A.** | shift+F1, shift+F2, ..., shift+F9,  shift+F10
Previous slot | **N.A.** | shift+-
Next slot | **N.A.** | shift++
Switch slot (**already done this way**) | 0, 1, 2...9 | 0, 1, 2...9

Indeed, it would be really really really really really (yeah 5 reallys) useful for memory digging.

**Comment by leiradel** [comment]
Fixed in https://github.com/leiradel/RASuite/commit/224c1650281b22699e3ad80466c626d923c07873
