### ISSUE TITLE
Recently opened files with core auto load

### ISSUE THREAD

**Issue by JuliaWolska** [leiradel/RASuite#13]
That would allow very convenient switching between games if you are working on multiple different projects. Right now first you need to load the core and then browse the file, and if different files you are using are in places that are not close, it's a bit uncomfortable to change the location everytime you are approaching different game.

**Comment by leiradel** [comment]
Added in https://github.com/leiradel/RASuite/commit/e26f2479b0721fdccc42fada4878975309e1b00c
