### ISSUE TITLE
Super Nintendo (snes9x core) use different MD5 file checksums

### ISSUE THREAD

**Issue by Altomar79** [leiradel/RASuite#16]
RASnes9x detect different checksum than RALibretro. I've also looked at [Online MD5 File Checksum](https://emn178.github.io/online-tools/md5_checksum.html)  to confirm that only RALibretro give different checksum. Though if i use the same core on retroarch (snes9x) the achievements load correctly.

**Comment by leiradel** [comment]
Fixed in https://github.com/leiradel/RASuite/commit/1ce12977fa4cae2d78b59048ee131563af4bf865
