### ISSUE TITLE
Create "Screenshots" folder if it doesn't exist

### ISSUE THREAD

**Issue by meleu** [leiradel/RASuite#17]
Looks like when there isn't a directory named **`Screenshots`**, the PrintScreen key don't do its job. After creating that dir, the screenshot feature starts to work.

It was reported by @ikki5 on discord.

Related to #10

**Comment by leiradel** [comment]
All the necessary folders are automatically created as in https://github.com/leiradel/RASuite/commit/61874c0a3a49ff73e3736162c6300c1657d41b89
