### ISSUE TITLE
disable some features when in hardcore mode

### ISSUE THREAD

**Issue by meleu** [leiradel/RASuite#2]
IMO this is one of the most (if not **THE** most) important issue to solve before spreading the word about RALibretro:

disable the following features when in hardcore mode:
- frame-by-frame
- load/save state

**Comment by meleu** [comment]
Tested latest builds (04/february/2018):
- pause emulation and frame-by-frame feature doesn't work on hardcore mode. Done! Solved! 👍 
- load/save state. It still works when in hardcore mode.

**Comment by leiradel** [comment]
Fixed in https://github.com/leiradel/RASuite/commit/9683b3fbc13951bc05954063657fec0da5bb4d37
