### ISSUE TITLE
something weird on "Load Recent" code

### ISSUE THREAD

**Issue by meleu** [leiradel/RASuite#23]
There's something weird with the "Load Recent" code. I'm not sure if it's happening because I'm using a virtual machine and/or because the ROMs are stored as if they were on a network driver...

Check it out:

![ralibretro-recent](https://user-images.githubusercontent.com/8508804/36851742-b9572f5c-1d48-11e8-8ace-c93415ea102c.png)

**Comment by leiradel** [comment]
Odd. How can I reproduce the issue?

**Comment by leiradel** [comment]
Is this a Windows VM or Wine?

**Comment by meleu** [comment]
> Is this a Windows VM or Wine?

It's a Windows 7 on a virtual machine (using VirtualBox).

> How can I reproduce the issue?

Not sure. Try to put some ROMs on a network drive and load them on RALibretro. And then try to load them on "Load Recent" menu.

**Comment by leiradel** [comment]
This is a bug with the serialization code.
