### ISSUE TITLE
RALibRetro Clone Achievement crashes program

### ISSUE THREAD

**Issue by grenade44** [leiradel/RASuite#24]
I tried cloning a achievement I made in the atari 2600 core and it just crashes the whole program.

**Comment by leiradel** [comment]
I take it only happens with the Atari 2600 core right?

**Comment by grenade44** [comment]
just tested with handy and that works fine

**Comment by meleu** [comment]
Unable to reproduce here. I used the "Clone Selected" button several times when working on my Atari 2600 sets and it works just fine.

**Comment by leiradel** [comment]
@meleu Thanks for your help.

@grenade44 I'm closing this issue. If it happens again, please reopen it and add the steps necessary to reproduce it.

**Comment by grenade44** [comment]
Just downloaded latest build and works fine for me now.

**Comment by leiradel** [comment]
Great, thanks for the report.
