### ISSUE TITLE
enable "Pause on Reset/Trigger" options

### ISSUE THREAD

**Issue by meleu** [leiradel/RASuite#26]
Please please please, make the "Pause on Reset" and Pause on Trigger" options work on RALibretro.

The "Pause on Reset" option is **HUUUUUUUUUUGE** help to debug cheevos.

Some screenshots of what I am talking about:

![pauseonreset](https://user-images.githubusercontent.com/8508804/37227261-7c6dbe52-23bb-11e8-8f9d-782e61766cf0.png)

![pauseontrigger](https://user-images.githubusercontent.com/8508804/37227263-7c94d21c-23bb-11e8-999c-18a14f507116.png)

**Comment by meleu** [comment]
tagging guys that can possibly lend a hand: @GameDragon2k and @Jamiras

**Comment by meleu** [comment]
Ooops! They're already working... Sorry guys.

Will try to investigate why they didn't work on my first tests.

Closing the issue.

**Comment by Jamiras** [comment]
One possible issue is that the achievement wasn't active. If it's not active, it won't Trigger or Reset, so it won't Pause on either.

**Comment by Jamiras** [comment]
Another possibility is that the achievement wasn't in the selected set. If you have an active achievement in Local, but are viewing Unofficial or Core, the Local achievement isn't being processed.
