### ISSUE TITLE
Leaderboards (Raspberry Pi)

### ISSUE THREAD

**Issue by enzyme-1** [leiradel/RASuite#28]
This issue is in regards to the leaderboard for [Batman](http://retroachievements.org/Game/1458) and it's inability to follow the '**_cancel_**' command when activated in RetroArch/RPi. The cancel command was changed to the current input when the score was found to multiply or add after resetting the game without losing a life. The new condition works and resolved the score adding on the RANes, but I am now getting reports that this is still happening in RetroArch.

This also tells me that the line for **_cancel_** may be being ignored for all leaderboards on RetroArch, but maybe only NES titles? I didn't have time this week to find a solution to resolve this, but I was looking around for anything related to this and decided to post here as an official troubleshooter (could be applied to all leaderboards concerning RPi). I will continue to post to this topic and edit this lead post as a reserved post if I find anything, but if anyone has any idea what is happening with RetroArch and leaderboards, feel free to add any helpful tips.

**Comment by leiradel** [comment]
Can you open this issue in the [RetroArch repository](https://github.com/libretro/RetroArch)? Thanks.

**Comment by meleu** [comment]
Maybe @celerizer would like to know about such incompatibilities...
