### ISSUE TITLE
sound issues

### ISSUE THREAD

**Issue by meleu** [leiradel/RASuite#29]
Looks like there are some users having problems with RALibretro sound:
http://retroachievements.org/viewtopic.php?t=6290&c=

**Comment by leiradel** [comment]
Can they provide the log?

**Comment by meleu** [comment]
Here is the log: https://ghostbin.com/paste/np5fx

He also recorded the sound so you can listen:
https://soundcloud.com/eduardo-cosmao/dino

**Comment by meleu** [comment]
The user said he cleaned and then updated his drivers and RALibretro is running fine now.

Closing this issue.

**Comment by leiradel** [comment]
Can we have this tip in the RALibretro documentation? Thanks!
