### ISSUE TITLE
NES memory is shorter on RALibretro/FCEUmm

### ISSUE THREAD

**Issue by meleu** [leiradel/RASuite#3]
When I load a game for NES on RANes and open the Memory Inspector, it says: "Aware of 65536 RAM locations"

Doing the same on RALibretro/FCEUmm, the Inspector says: "Aware of 2048 RAM locations"

And, indeed, on RALibretro addresses greater than `0x07ff` are not shown on Memory Inspector.

Therefore, cheevos referencing addresses beyond `0x07ff` don't work on RALibretro.

I wonder if it has something to do with the [Memory Mirroring thing](https://wiki.nesdev.com/w/index.php/Mirroring#Memory_Mirroring).

**Comment by meleu** [comment]
Testing the latest (4/february/2018) build I noticed the Memory Inspector in RALibretro/FCEUmm now says:
"Aware of 8192 RAM locations"

Looks like you multiplied the RAM size by 4:
2048 * 4 = 8192

But to make it have the same size as RANes you would need to multiply the RAM size by 2^5 (32):
2048 * 32 = 65536

**Comment by leiradel** [comment]
The system RAM is not mirrored throughout the entire address space. I have to make a dummy map from 0x2000 to 0x5fff, and then map the Save RAM starting at 0x6000, without mirrors.

**Comment by leiradel** [comment]
Fixed in https://github.com/leiradel/RASuite/commit/2bd600248a49ab8ccacbd77c2d835102a25eb265

**Comment by meleu** [comment]
**WOW!!** :flushed: 

What a fancy coat!!
