### ISSUE TITLE
Frame skip

### ISSUE THREAD

**Issue by Jamiras** [leiradel/RASuite#33]
Ability to advance the emulator by one frame at a time. RANes does this with backslash.

Should be limited to softcore mode.

**Comment by meleu** [comment]
@Jamiras it can be done with `;`. For more info about shortcuts check https://retroachievements.github.io/docs/RALibretro/#keyboard-shortcuts

**Comment by Jamiras** [comment]
Ah, thank you. Verified, but it only seems to work if the emulator is paused. It doesn't "automatically pause emulation" as suggested in the documentation.

**Comment by meleu** [comment]
> It doesn't "automatically pause emulation" as suggested in the documentation.

oh, you're right. but it was working as described in the documentation on the very first versions of RALibretro... Let's see what changed.

**Comment by leiradel** [comment]
The previous behavior was put back in https://github.com/leiradel/RASuite/commit/e7bec26a6cb246dec85e9922fb07c09e87211597
