### ISSUE TITLE
Ability to set window size as a multiplier of resolution for selected core

### ISSUE THREAD

**Issue by Jamiras** [leiradel/RASuite#34]
This seems like a fairly standard feature in the other emulators. 1x, 2x, 3x, 4x. 
Forcing the aspect ratio to 4:3 or 8:7 PAR causes some pixel lines to be wider than others. 
Disabling preserve aspect ratio allows for manual sizing, but getting it exactly right is hard and it resets every time you open the emulator.

**Comment by leiradel** [comment]
Added in https://github.com/leiradel/RASuite/commit/3e8f8ceedcc80fed3c0e85e97da4ed9818f42ace
