### ISSUE TITLE
[feature reqeuest] name of active core on window's title

### ISSUE THREAD

**Issue by meleu** [leiradel/RASuite#4]
It would be "user-friendly" to provide some indication of what core is active.

I suggest putting the core name on window's title. Like `RALibretro/CoreName - version - username`, and `RALibretro/no core - ...` when there isn't any core selected.

Examples:
- `RALibretro/PicoDrive - 1.0 - meleu`
- `RALibretro/FCEUmm - 1.0 - meleu`
- `RALibretro/Handy - 1.0 - meleu`
- `RALibretro/no core - 1.0 - meleu`

![ralibretro-window-title](https://user-images.githubusercontent.com/8508804/35770629-00aaa002-0906-11e8-8db1-b5b4575cdc10.png)

**Comment by leiradel** [comment]
Unfortunately the integration DLL also changes the window title, making it hard to change it everytime the core is changed.

**Comment by meleu** [comment]
@leiradel I'm unable to reopen this issue...

Just to remember what @GameDragon2k said on discord:

> `RA_UpdateAppTitle()` is an optional function. You can just call it to change the title when you load a core.

**Comment by meleu** [comment]
@loopyd said in discord that he has interest in taking a look at RALibretro code :)

**Comment by leiradel** [comment]
Fixed in https://github.com/leiradel/RASuite/commit/74feb50ae661503f5ea20154f738c7e2756ed802
