### ISSUE TITLE
RALibretro freezes when disabling hardcore mode without any game loaded

### ISSUE THREAD

**Issue by meleu** [leiradel/RASuite#7]
pretty much what the title says.

Ways to reproduce:
1. Open RALibretro
2. Provide RetroAchievements account info (this won't happen if you saved your password)
3. Go to RetroAchievements menu and enable/disable Hardcore mode

This also happens if you select a core but don't load any game.

This doesn't happen on the official emulators.

**Comment by leiradel** [comment]
Fixed in https://github.com/leiradel/RASuite/commit/9e72c0b25259567fa10a2541e5d6f22ba08169c6
