### ISSUE TITLE
RALibretro doesn't accept more than 3 keyboard inputs

### ISSUE THREAD

**Issue by meleu** [leiradel/RASuite#8]
In the game After Burner 2 (Mega Drive) there's a cheat to select stage:
Keep pressed `A`+`B`+`C` and then press `Start`.

I use this trick normally on RAGens, but I'm not able to perform it on RALibretro. Only tried with a keyboard, not sure if it's an issue with a gamepad.

Easy way to reproduce/confirm this issue:
1. Start any game where there's a menu on the title screen
2. Keep pressed `A`+`B` and try to go up/down in the menu with the d-pad. You'll see it works.
3. Keep pressed `A`+`B`+`C` and try to go up/down in the menu with the d-pad. You'll see it does NOT work.

Tested the same thing on other cores, same issue (I mean, it's not picodrive only).

**Comment by leiradel** [comment]
It seems your keyboard doesn't register those three keys. Can you test with a different keyboard?

**Comment by meleu** [comment]
As I said in the OP, this issue does NOT happens on RAGens. Therefore I have a strong conviction that the problem is not on my keyboard. :wink:

**Comment by leiradel** [comment]
You're right, sorry. RALibretro doesn't artificially limit the number of simultaneous key presses, so the problem is somewhere else. I'll make some tests.

**Comment by leiradel** [comment]
Which keyboard keys are you using?

I've tested with Z, X, C, and UP and Down and it worked just fine. I had to hold six keys at the same time to make the keyboard stop responding to other keypresses. I can reproduce it even in a terminal.

Are you using the same key bindings in RAGens?

**Comment by meleu** [comment]
@JuliaWolska could you please try to reproduce the issue I describe on the OP?

I'm starting to believe it has something to do with me using a virtual machine...

**Comment by JuliaWolska** [comment]
It works when you press and hold a+x+c (keyboard keys)

**Comment by leiradel** [comment]
@meleu is this really an issue?

**Comment by meleu** [comment]
well, not being able to use all those key pressings at the same time is an issue. But I'm not 100% sure that it is a RALibretro issue.

I'm closing this issue so you don't have to worry about it. When I confirm it's a RALibretro limitation I ping you again.
