### ISSUE TITLE
Emulation Slowdown on AMD GPU

### ISSUE THREAD

**Issue by kdecks** [leiradel/RASuite#9]
I'm on the newest (Salsa's) package and exe, both updated 2 and 3 February 2018.

Performance for SNES, Gens, NES; likely everything, play at about 60% speed with audio chirping. Donkey Kong Country 2 crashes when I attempt to run it.

My best guess is it's related to my video card, AMD Radeon HD 6900. Drivers are current. I've tested disabling the video card and performance is exactly the same, meaning it's not getting used at all.
Compared to Retroarch GL performance is good. But when I turned off the video card and tested it Retroarch would not run.

I.e.: My assumption is that my system isn't attempting to use GL though my card at all.

**Comment by kdecks** [comment]
I've updated today to latest. Issue resolved.

It's been a while since I've updated, the games I tested worked as they should now. One of the recent changes must have corrected whatever the issue was.

**Comment by meleu** [comment]
**yoohool!** that's great!
